spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=Pass123a
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway will look in db/migration by default
spring.flyway.enabled=true

# Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# OpenAPI/Swagger Configuration
spring.application.name=Grocieries API
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
